generated_at: '2025-09-29T13:48:09.398363'
node: pve
storage_details:
- name: LVM-SSD
  type: lvmthin
  enabled: true
  content:
  - rootdir
  - images
  total_gb: 912.76
  used_gb: 152.71
  available_gb: 760.06
  usage_percent: 16.73
- name: DIR02
  type: dir
  enabled: true
  content:
  - images
  - snippets
  - vztmpl
  - rootdir
  - backup
  - iso
  total_gb: 7392.19
  used_gb: 142.34
  available_gb: 6877.23
  usage_percent: 1.93
- name: DIR03
  type: dir
  enabled: true
  content:
  - vztmpl
  - snippets
  - images
  - iso
  - backup
  - rootdir
  total_gb: 7392.19
  used_gb: 0.0
  available_gb: 7019.57
  usage_percent: 0.0
- name: local-lvm
  type: lvmthin
  enabled: true
  content:
  - rootdir
  - images
  total_gb: 141.23
  used_gb: 0.0
  available_gb: 141.23
  usage_percent: 0.0
- name: local
  type: dir
  enabled: true
  content:
  - iso
  - backup
  - snippets
  - images
  - vztmpl
  total_gb: 67.73
  used_gb: 47.05
  available_gb: 17.19
  usage_percent: 69.47
