vmid: 207
name: caldera
memory_mb: '8096'
cores: 2
sockets: 1
network_interfaces:
- interface: net0
  bridge: vmbr2
  firewall: '1'
disks:
- name: ide2
- name: scsi0
  storage: LVM-SSD
  size: 50G
- name: scsihw
node: pve
