cores: 2
disks:
- name: ide2
  size: 5261680K
  storage: local
- name: ide0
  size: 771138K
  storage: local
- name: virtio0
  size: 64G
  storage: DIR02
- name: scsihw
memory_mb: '4096'
name: winClient1
network_interfaces:
- bridge: vmbr2
  firewall: '1'
  interface: net0
  vlan: '20'
node: pve
sockets: 1
vmid: 213
