vmid: 213
name: winClient1
memory_mb: '4096'
cores: 2
sockets: 1
network_interfaces:
- interface: net0
  bridge: vmbr2
  firewall: '1'
  vlan: '20'
disks:
- name: ide0
  storage: local
  size: 771138K
- name: virtio0
  storage: DIR02
  size: 64G
- name: scsihw
- name: ide2
  storage: local
  size: 5261680K
node: pve
