vmid: 208
name: securityOnion
memory_mb: '16384'
cores: 4
sockets: 1
network_interfaces:
- interface: net2
  bridge: vmbr5
- interface: net1
  bridge: vmbr4
- interface: net0
  bridge: vmbr2
  firewall: '1'
disks:
- name: scsi0
  storage: LVM-SSD
  size: 300G
- name: ide2
  storage: local
  size: 13690M
- name: scsihw
node: pve
