cores: 1
disks:
- name: ide2
- name: ide0
  size: 32G
  storage: local
- name: scsihw
memory_mb: '2048'
name: metasploitable
network_interfaces:
- bridge: vmbr2
  firewall: '1'
  interface: net0
  vlan: '10'
node: pve
sockets: 1
vmid: 204
