vmid: 204
name: metasploitable
memory_mb: '2048'
cores: 1
sockets: 1
network_interfaces:
- interface: net0
  bridge: vmbr2
  firewall: '1'
  vlan: '10'
disks:
- name: ide2
- name: ide0
  storage: local
  size: 32G
- name: scsihw
node: pve
