vms:
- vmid: 201
  name: pfFirewall
  memory_mb: '2048'
  cores: 4
  sockets: 1
  network_interfaces:
  - interface: net0
    bridge: vmbr0
    firewall: '1'
  - interface: net1
    bridge: vmbr2
    firewall: '1'
  disks:
  - name: ide2
    storage: local
    size: 966536K
  - name: scsi0
    storage: LVM-SSD
    size: 32G
  - name: scsihw
  node: pve
- vmid: 202
  name: kaliMachine
  memory_mb: '8192'
  cores: 4
  sockets: 1
  network_interfaces:
  - interface: net0
    bridge: vmbr2
    firewall: '1'
  disks:
  - name: ide2
    storage: local
    size: 4335408K
  - name: scsihw
  - name: scsi0
    storage: LVM-SSD
    size: 80G
  node: pve
- vmid: 203
  name: docker-server
  memory_mb: '9536'
  cores: 2
  sockets: 2
  network_interfaces:
  - interface: net0
    bridge: vmbr2
    firewall: '1'
    vlan: '30'
  disks:
  - name: scsi0
    storage: LVM-SSD
    size: 160G
  - name: scsihw
  - name: ide2
  node: pve
- vmid: 204
  name: metasploitable
  memory_mb: '2048'
  cores: 1
  sockets: 1
  network_interfaces:
  - interface: net0
    bridge: vmbr2
    firewall: '1'
    vlan: '10'
  disks:
  - name: scsihw
  - name: ide0
    storage: local
    size: 32G
  - name: ide2
  node: pve
- vmid: 205
  name: wazuhServer
  memory_mb: '8192'
  cores: 4
  sockets: 1
  network_interfaces:
  - interface: net0
    bridge: vmbr2
    firewall: '1'
  disks:
  - name: scsi0
    storage: DIR02
    size: 160G
  - name: scsihw
  - name: ide2
  node: pve
- vmid: 206
  name: nessusMachine
  memory_mb: '4096'
  cores: 4
  sockets: 1
  network_interfaces:
  - interface: net0
    bridge: vmbr2
    firewall: '1'
  disks:
  - name: ide2
  - name: scsi0
    storage: LVM-SSD
    size: 40G
  - name: scsihw
  node: pve
- vmid: 207
  name: caldera
  memory_mb: '8096'
  cores: 2
  sockets: 1
  network_interfaces:
  - interface: net0
    bridge: vmbr2
    firewall: '1'
  disks:
  - name: ide2
  - name: scsi0
    storage: LVM-SSD
    size: 50G
  - name: scsihw
  node: pve
- vmid: 208
  name: securityOnion
  memory_mb: '16384'
  cores: 4
  sockets: 1
  network_interfaces:
  - interface: net1
    bridge: vmbr4
  - interface: net2
    bridge: vmbr5
  - interface: net0
    bridge: vmbr2
    firewall: '1'
  disks:
  - name: scsihw
  - name: scsi0
    storage: LVM-SSD
    size: 300G
  - name: ide2
    storage: local
    size: 13690M
  node: pve
- vmid: 210
  name: ubuntuAgent
  memory_mb: '4086'
  cores: 2
  sockets: 1
  network_interfaces:
  - interface: net0
    bridge: vmbr2
    firewall: '1'
    vlan: '30'
  disks:
  - name: scsi0
    storage: LVM-SSD
    size: 40G
  - name: scsihw
  - name: ide2
  node: pve
- vmid: 211
  name: AdServer
  memory_mb: '4096'
  cores: 4
  sockets: 1
  network_interfaces:
  - interface: net0
    bridge: vmbr2
    firewall: '1'
    vlan: '20'
  disks:
  - name: ide2
  - name: virtio0
    storage: LVM-SSD
    size: 50G
  - name: ide0
  - name: scsihw
  node: pve
- vmid: 213
  name: winClient1
  memory_mb: '4096'
  cores: 2
  sockets: 1
  network_interfaces:
  - interface: net0
    bridge: vmbr2
    firewall: '1'
    vlan: '20'
  disks:
  - name: ide0
    storage: local
    size: 771138K
  - name: scsihw
  - name: virtio0
    storage: DIR02
    size: 64G
  - name: ide2
    storage: local
    size: 5261680K
  node: pve
generated_at: '2025-10-01T08:16:04.447281'
