generated_at: '2025-09-29T09:55:03.245205'
vms:
- cores: 4
  disks:
  - name: scsihw
  - name: scsi0
    size: 32G
    storage: LVM-SSD
  - name: ide2
    size: 966536K
    storage: local
  memory_mb: '2048'
  name: pfFirewall
  network_interfaces:
  - bridge: vmbr0
    firewall: '1'
    interface: net0
  - bridge: vmbr2
    firewall: '1'
    interface: net1
  node: pve
  sockets: 1
  vmid: 201
- cores: 4
  disks:
  - name: scsihw
  - name: scsi0
    size: 80G
    storage: LVM-SSD
  - name: ide2
    size: 4335408K
    storage: local
  memory_mb: '8192'
  name: kaliMachine
  network_interfaces:
  - bridge: vmbr2
    firewall: '1'
    interface: net0
  node: pve
  sockets: 1
  vmid: 202
- cores: 2
  disks:
  - name: scsihw
  - name: ide2
  - name: scsi0
    size: 160G
    storage: LVM-SSD
  memory_mb: '9536'
  name: docker-server
  network_interfaces:
  - bridge: vmbr2
    firewall: '1'
    interface: net0
    vlan: '30'
  node: pve
  sockets: 2
  vmid: 203
- cores: 1
  disks:
  - name: scsihw
  - name: ide0
    size: 32G
    storage: file=local
  - name: ide2
  memory_mb: '2048'
  name: metasploitable
  network_interfaces:
  - bridge: vmbr2
    firewall: '1'
    interface: net0
    vlan: '10'
  node: pve
  sockets: 1
  vmid: 204
- cores: 4
  disks:
  - name: scsihw
  - name: ide2
  - name: scsi0
    size: 160G
    storage: DIR02
  memory_mb: '8192'
  name: wazuhServer
  network_interfaces:
  - bridge: vmbr2
    firewall: '1'
    interface: net0
  node: pve
  sockets: 1
  vmid: 205
- cores: 4
  disks:
  - name: scsi0
    size: 40G
    storage: LVM-SSD
  - name: ide2
  - name: scsihw
  memory_mb: '4096'
  name: nessusMachine
  network_interfaces:
  - bridge: vmbr2
    firewall: '1'
    interface: net0
  node: pve
  sockets: 1
  vmid: 206
- cores: 2
  disks:
  - name: ide2
  - name: scsi0
    size: 50G
    storage: LVM-SSD
  - name: scsihw
  memory_mb: '8096'
  name: caldera
  network_interfaces:
  - bridge: vmbr2
    firewall: '1'
    interface: net0
  node: pve
  sockets: 1
  vmid: 207
- cores: 4
  disks:
  - name: ide2
    size: 13690M
    storage: local
  - name: scsi0
    size: 300G
    storage: LVM-SSD
  - name: scsihw
  memory_mb: '16384'
  name: securityOnion
  network_interfaces:
  - bridge: vmbr4
    interface: net1
  - bridge: vmbr5
    interface: net2
  - bridge: vmbr2
    firewall: '1'
    interface: net0
  node: pve
  sockets: 1
  vmid: 208
- cores: 2
  disks:
  - name: scsihw
  - name: ide2
  - name: scsi0
    size: 40G
    storage: LVM-SSD
  memory_mb: '4086'
  name: ubuntuAgent
  network_interfaces:
  - bridge: vmbr2
    firewall: '1'
    interface: net0
    vlan: '30'
  node: pve
  sockets: 1
  vmid: 210
- cores: 4
  disks:
  - name: ide0
  - name: scsihw
  - name: virtio0
    size: 50G
    storage: LVM-SSD
  - name: ide2
  memory_mb: '4096'
  name: AdServer
  network_interfaces:
  - bridge: vmbr2
    firewall: '1'
    interface: net0
    vlan: '20'
  node: pve
  sockets: 1
  vmid: 211
- cores: 2
  disks:
  - name: ide0
    size: 771138K
    storage: local
  - name: virtio0
    size: 64G
    storage: DIR02
  - name: scsihw
  - name: ide2
    size: 5261680K
    storage: local
  memory_mb: '4096'
  name: winClient1
  network_interfaces:
  - bridge: vmbr2
    firewall: '1'
    interface: net0
    vlan: '20'
  node: pve
  sockets: 1
  vmid: 213
