vmid: 203
name: docker-server
memory_mb: '9536'
cores: 2
sockets: 2
network_interfaces:
- interface: net0
  bridge: vmbr2
  firewall: '1'
  vlan: '30'
disks:
- name: scsihw
- name: ide2
- name: scsi0
  storage: LVM-SSD
  size: 160G
node: pve
